/**
 * Fixed interface text of the public site. Content (names, about, address…)
 * comes from SiteSettings and the catalog, never from here.
 */
export type Lang = 'ar' | 'en';

export const strings = {
  ar: {
    salonType: 'صالون نسائي',
    defaultSalonName: 'سوسو صالون نسائي',
    defaultTagline: 'جمالك شغفنا',
    skipToContent: 'تخطي إلى المحتوى',
    nav: {
      home: 'الرئيسية',
      services: 'الخدمات',
      about: 'عن الصالون',
      gallery: 'المعرض',
      contact: 'تواصلي معنا',
    },
    mainNav: 'القائمة الرئيسية',
    menu: 'القائمة',
    closeMenu: 'إغلاق القائمة',
    otherLang: { label: 'EN', name: 'English', href: '/en', lang: 'en' },
    whatsappCta: 'تواصلي عبر واتساب',
    browseServices: 'استعرضي الخدمات',
    servicesTitle: 'خدماتنا',
    servicesLead: 'اختاري الخدمة التي تناسبك، في الصالون أو في منزلك.',
    tabsLabel: 'مكان الخدمة',
    tabs: { all: 'الكل', salon: 'في الصالون', home: 'خدمة منزلية' },
    categoriesLabel: 'الفئات',
    allCategories: 'كل الفئات',
    emptyFilter: 'لا توجد خدمات في هذا التصنيف حالياً.',
    badgeSalon: 'في الصالون',
    badgeHome: 'خدمة منزلية',
    askOnWhatsapp: 'اطلبي عبر واتساب',
    askOnWhatsappFor: (name: string) => `اطلبي ${name} عبر واتساب`,
    aboutTitle: 'عن الصالون',
    brandStrip: 'هوية الصالون',
    galleryTitle: 'من داخل الصالون',
    openImage: (alt: string) => `تكبير الصورة: ${alt}`,
    closeImage: 'إغلاق',
    previousImage: 'الصورة السابقة',
    nextImage: 'الصورة التالية',
    contactTitle: 'تواصلي معنا',
    address: 'العنوان',
    workingHours: 'ساعات العمل',
    phone: 'الهاتف',
    whatsapp: 'واتساب',
    instagram: 'انستقرام',
    openMap: 'افتحي الموقع على الخريطة',
    mapTitle: 'موقع الصالون على الخريطة',
    rights: 'جميع الحقوق محفوظة',
    followInstagram: 'تابعينا على انستقرام',
  },
  en: {
    salonType: 'Ladies Salon',
    defaultSalonName: 'Soso Ladies Salon',
    defaultTagline: 'جمالك شغفنا',
    skipToContent: 'Skip to content',
    nav: {
      home: 'Home',
      services: 'Services',
      about: 'About',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    mainNav: 'Main menu',
    menu: 'Menu',
    closeMenu: 'Close menu',
    otherLang: { label: 'عربي', name: 'العربية', href: '/', lang: 'ar' },
    whatsappCta: 'Chat on WhatsApp',
    browseServices: 'Browse services',
    servicesTitle: 'Our services',
    servicesLead: 'Choose the service that suits you, at the salon or at home.',
    tabsLabel: 'Service location',
    tabs: { all: 'All', salon: 'At the salon', home: 'Home service' },
    categoriesLabel: 'Categories',
    allCategories: 'All categories',
    emptyFilter: 'No services in this category yet.',
    badgeSalon: 'At the salon',
    badgeHome: 'Home service',
    askOnWhatsapp: 'Ask on WhatsApp',
    askOnWhatsappFor: (name: string) => `Ask about ${name} on WhatsApp`,
    aboutTitle: 'About the salon',
    brandStrip: 'Salon identity',
    galleryTitle: 'Inside the salon',
    openImage: (alt: string) => `Enlarge image: ${alt}`,
    closeImage: 'Close',
    previousImage: 'Previous image',
    nextImage: 'Next image',
    contactTitle: 'Contact us',
    address: 'Address',
    workingHours: 'Working hours',
    phone: 'Phone',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    openMap: 'Open the location on the map',
    mapTitle: 'Salon location on the map',
    rights: 'All rights reserved',
    followInstagram: 'Follow us on Instagram',
  },
} as const;

export type Strings = (typeof strings)[Lang];
