/**
 * Fixed interface text of the public site. Content that the owner edits
 * (services, contact details) comes from SiteSettings and the catalog; the
 * homepage copy below is the approved redesign copy (October 2026).
 */
export type Lang = 'ar' | 'en';

export type Occasion = 'bride' | 'evening' | 'eid';

export const strings = {
  ar: {
    salonType: 'صالون نسائي',
    defaultSalonName: 'سوسو صالون نسائي',
    defaultTagline: 'جمالك شغفنا',
    galleryTitle: 'من داخل الصالون',
    skipToContent: 'تخطي إلى المحتوى',
    nav: {
      home: 'الرئيسية',
      services: 'الخدمات',
      homeService: 'خدمة منزلية',
      about: 'عن سوسو',
      gallery: 'المعرض',
      contact: 'تواصلي معنا',
    },
    breadcrumb: 'مسار الصفحة',
    mainNav: 'القائمة الرئيسية',
    menu: 'القائمة',
    closeMenu: 'إغلاق القائمة',
    otherLang: { label: 'EN', name: 'English', href: '/en', lang: 'en' },
    bookOnWhatsapp: 'احجزي عبر واتساب',
    hero: {
      eyebrow: 'صالون نسائي · الدوحة',
      titleLines: ['جمالكِ', 'شغفنا'],
      body: 'مكياج، شعر، حنة وعناية بالأظافر على يد خبيرات، في أجواء نسائية خاصة، أو نصل إليكِ أينما كنتِ.',
      cta: 'احجزي الآن عبر واتساب',
      segmentLabel: 'مكان الخدمة',
      segment: { salon: 'في الصالون', home: 'في بيتك' },
    },
    statement: {
      line1: 'نعتني بكِ كما لو كنتِ',
      line2: 'ضيفةً في بيتنا.',
      body: 'صالون سوسو مكان نسائي بالكامل، هادئ وخاص. وإذا كانت راحتك في بيتك، نأتيكِ بكامل الأدوات وبنفس العناية.',
      facts: [
        ['نسائي', 'بالكامل'],
        ['خدمة منزلية', 'في الدوحة'],
        ['حجز مباشر', 'عبر واتساب'],
      ],
    },
    marqueeLabel: 'خدماتنا',
    services: {
      eyebrow: 'خدماتنا',
      titleLines: ['كل ما تحتاجينه،', 'في مكان واحد.'],
      intro: 'اختاري الخدمة، ثم اسألينا عن الباقة التي تناسب مناسبتك.',
      filterLabel: 'مكان الخدمة',
      filter: { all: 'الكل', salon: 'في الصالون', home: 'خدمة منزلية' },
      tag: { BOTH: 'صالون · منزلي', SALON: 'في الصالون', HOME: 'خدمة منزلية' },
      cta: 'اسألي عن الباقات',
      ctaFor: (name: string) => `اسألي عن باقات ${name} عبر واتساب`,
      empty: 'لا توجد خدمات في هذا الاختيار حالياً.',
      photoSoon: 'صورة قريباً',
    },
    signature: {
      eyebrow: 'خدمتنا المميزة',
      title: 'المكياج الدائم',
      body: 'حواجب، آيلاينر وشفاه بلمسة طبيعية تدوم، لتستيقظي كل صباح جاهزة.',
      cta: 'احجزي استشارة مجانية',
      imageAlt: 'جلسة عناية بالبشرة في الصالون',
    },
    occasions: {
      eyebrow: 'مناسباتك',
      titleLines: ['لكل مناسبة', 'إطلالتها.'],
      bride: 'العروس',
      brideSub: 'باقة متكاملة ليوم العمر',
      evening: 'السهرة',
      eid: 'العيد والمناسبات',
      // The occasion as it reads inside the prefilled WhatsApp message.
      inMessage: { bride: 'العروس', evening: 'السهرة', eid: 'العيد والمناسبات' },
      askFor: (occasion: string) => `اسألي عن تجهيزات ${occasion} عبر واتساب`,
    },
    why: {
      eyebrow: 'لماذا سوسو؟',
      titleLines: ['تفاصيل صغيرة،', 'فرق كبير.'],
      items: [
        { title: 'خصوصية تامة', text: 'مكان نسائي بالكامل، هادئ وخاص بكِ.' },
        { title: 'عناية بالتفاصيل', text: 'نهتم بكل تفصيلة تُبرز جمالك.' },
        { title: 'نصل إليكِ', text: 'خدمة منزلية بكامل الأدوات في الدوحة.' },
        { title: 'تواصل سهل', text: 'رسالة واتساب واحدة تكفي.' },
      ],
    },
    how: {
      eyebrow: 'كيف تطلبين خدمتك؟',
      title: 'ثلاث خطوات فقط.',
      items: [
        { title: 'اختاري خدمتك', text: 'تصفّحي خدماتنا واختاري ما يناسبك.' },
        { title: 'راسلينا على واتساب', text: 'اسألي عن التفاصيل والمواعيد المتاحة.' },
        { title: 'استمتعي بالتجربة', text: 'في الصالون أو في راحة منزلك.' },
      ],
    },
    cta: {
      titleLines: ['جاهزة', 'لإطلالتك الجديدة؟'],
      body: 'راسلينا الآن ونرتّب لك موعدك في الصالون أو في بيتك.',
      button: 'احجزي عبر واتساب',
    },
    footer: {
      address: 'العنوان',
      hours: 'ساعات العمل',
      phone: 'الهاتف',
      instagram: 'انستقرام',
      whatsapp: 'واتساب',
      map: 'الموقع على الخريطة',
      copyright: '© 2026 Soso Ladies Salon · soso-ladies.qa',
    },
    sticky: {
      title: 'احجزي موعدك',
      sub: 'رد سريع عبر واتساب',
      button: 'واتساب',
    },
    messages: {
      booking: 'مرحباً سوسو، أرغب بحجز موعد.',
      service: (service: string) => `مرحباً سوسو، أرغب بالاستفسار عن باقات ${service}.`,
      consultation: 'مرحباً سوسو، أرغب بحجز استشارة مجانية للمكياج الدائم.',
      occasion: (occasion: string) => `مرحباً سوسو، أرغب بالاستفسار عن تجهيزات ${occasion}.`,
      homeVisit: 'مرحباً سوسو، أرغب بحجز خدمة منزلية.',
    },
    carousel: {
      label: 'لمحات من خدماتنا',
      slide: (i: number, n: number, name: string) => `${name}، الشريحة ${i} من ${n}`,
      goTo: (name: string) => `اعرضي: ${name}`,
      previous: 'الشريحة السابقة',
      next: 'الشريحة التالية',
      pause: 'إيقاف العرض',
      play: 'تشغيل العرض',
      slides: { makeup: 'المكياج', facial: 'العناية بالبشرة', hair: 'الشعر', henna: 'الحنة' },
    },
    browseServices: 'استعرضي الخدمات',
    allServices: 'كل الخدمات',
    learnMore: 'اعرفي المزيد',
    pages: {
      services: {
        eyebrow: 'خدماتنا',
        titleLines: ['كل ما تحتاجينه،', 'في مكان واحد.'],
        lead: 'اختاري الخدمة، ثم اسألينا عن الباقة التي تناسب مناسبتك.',
        imageAlt: 'عناية بالأظافر',
      },
      homeService: {
        eyebrow: 'خدمة منزلية · الدوحة',
        titleLines: ['نأتيكِ', 'أينما كنتِ.'],
        lead: 'إذا كانت راحتك في بيتك، نأتيكِ بكامل الأدوات وبنفس عناية الصالون.',
        imageAlt: 'خبيرة مكياج مع عميلة في منزلها',
      },
      about: {
        eyebrow: 'عن سوسو',
        titleLines: ['نعتني بكِ', 'كضيفةٍ في بيتنا.'],
        lead: 'صالون سوسو مكان نسائي بالكامل، هادئ وخاص.',
        imageAlt: 'تصفيف الشعر في الصالون',
      },
      gallery: {
        eyebrow: 'المعرض',
        titleLines: ['من داخل', 'سوسو.'],
        lead: 'لمحات من أجواء الصالون وخدماتنا.',
        imageAlt: 'نقش حنة على اليد',
      },
      contact: {
        eyebrow: 'تواصلي معنا',
        titleLines: ['يسعدنا', 'تواصلكِ.'],
        lead: 'راسلينا على واتساب ونرتّب لك موعدك في الصالون أو في بيتك.',
      },
    },
    servicesPreview: {
      eyebrow: 'خدماتنا',
      titleLines: ['كل ما تحتاجينه،', 'في مكان واحد.'],
    },
    homeTeaser: {
      eyebrow: 'خدمة منزلية',
      titleLines: ['نأتيكِ', 'أينما كنتِ.'],
      body: 'إذا كانت راحتك في بيتك، نأتيكِ بكامل الأدوات وبنفس العناية، في الدوحة.',
      cta: 'تفاصيل الخدمة المنزلية',
      imageAlt: 'خبيرة مكياج مع عميلة في منزلها',
    },
    homeVisit: {
      factsLabel: 'الخدمة المنزلية',
      facts: [
        ['نسائي', 'بالكامل'],
        ['بكامل', 'الأدوات'],
        ['في', 'الدوحة'],
      ],
      stepsEyebrow: 'كيف تعمل؟',
      stepsTitle: 'ثلاث خطوات فقط.',
      steps: [
        { title: 'اختاري الخدمة', text: 'تصفّحي الخدمات المتاحة في المنزل.' },
        { title: 'راسلينا على واتساب', text: 'حدّدي الموعد والعنوان المناسبين لكِ.' },
        { title: 'نصل إليكِ', text: 'بكامل الأدوات وبنفس عناية الصالون.' },
      ],
      servicesEyebrow: 'متاح في منزلك',
      servicesTitle: 'الخدمات المنزلية',
      cta: 'احجزي خدمة منزلية',
    },
    aboutPage: {
      storyEyebrow: 'قصتنا',
      videoEyebrow: 'لمحة من سوسو',
      videoTitle: 'من داخل الصالون.',
    },
    brandStrip: 'هوية الصالون',
    gallery: {
      open: (alt: string) => `تكبير الصورة: ${alt}`,
      close: 'إغلاق',
      previous: 'الصورة السابقة',
      next: 'الصورة التالية',
      alts: {
        makeup: 'خبيرة مكياج مع عميلة',
        facial: 'جلسة عناية بالبشرة',
        hair: 'تصفيف الشعر',
        henna: 'نقش حنة على اليد',
        manicure: 'عناية بالأظافر',
        pedicure: 'جلسة باديكير',
      },
    },
    contactPage: {
      whatsapp: 'واتساب',
      whatsappHint: 'أسرع طريقة للحجز',
      phone: 'الهاتف',
      instagram: 'انستقرام',
      address: 'العنوان',
      hours: 'ساعات العمل',
      openMap: 'افتحي الموقع على الخريطة',
      mapTitle: 'موقع الصالون على الخريطة',
      empty: 'تُضاف بيانات التواصل قريباً.',
    },
  },
  en: {
    salonType: 'Ladies Salon',
    defaultSalonName: 'Soso Ladies Salon',
    defaultTagline: 'جمالك شغفنا',
    galleryTitle: 'Inside the salon',
    skipToContent: 'Skip to content',
    nav: {
      home: 'Home',
      services: 'Services',
      homeService: 'Home service',
      about: 'About Soso',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    breadcrumb: 'Breadcrumb',
    mainNav: 'Main menu',
    menu: 'Menu',
    closeMenu: 'Close menu',
    otherLang: { label: 'ع', name: 'العربية', href: '/', lang: 'ar' },
    bookOnWhatsapp: 'Book on WhatsApp',
    hero: {
      eyebrow: 'Ladies salon · Doha',
      titleLines: ['Your beauty,', 'our passion'],
      body: 'Makeup, hair, henna and nail care by expert women, in a private ladies-only space, or brought to you wherever you are.',
      cta: 'Book now on WhatsApp',
      segmentLabel: 'Where to be served',
      segment: { salon: 'In the salon', home: 'At home' },
    },
    statement: {
      line1: 'We care for you as if you were',
      line2: 'a guest in our home.',
      body: 'Soso is a fully ladies-only salon, calm and private. And if home is where you are most comfortable, we come to you with everything we need and the same care.',
      facts: [
        ['Ladies', 'only'],
        ['Home service', 'across Doha'],
        ['Direct booking', 'on WhatsApp'],
      ],
    },
    marqueeLabel: 'Our services',
    services: {
      eyebrow: 'Our services',
      titleLines: ['Everything you need,', 'in one place.'],
      intro: 'Choose a service, then ask us about the package that suits your occasion.',
      filterLabel: 'Where to be served',
      filter: { all: 'All', salon: 'In the salon', home: 'At home' },
      tag: { BOTH: 'Salon · Home', SALON: 'Salon only', HOME: 'Home only' },
      cta: 'Ask about packages',
      ctaFor: (name: string) => `Ask about ${name} packages on WhatsApp`,
      empty: 'No services for this choice yet.',
      photoSoon: 'Photo coming soon',
    },
    signature: {
      eyebrow: 'Our signature service',
      title: 'Permanent makeup',
      body: 'Brows, eyeliner and lips with a natural finish that lasts, so you wake up ready every morning.',
      cta: 'Book a free consultation',
      imageAlt: 'A facial treatment at the salon',
    },
    occasions: {
      eyebrow: 'Your occasions',
      titleLines: ['Every occasion', 'has its look.'],
      bride: 'The bride',
      brideSub: 'A complete package for your big day',
      evening: 'Evening out',
      eid: 'Eid and occasions',
      inMessage: { bride: 'bridal', evening: 'evening', eid: 'Eid and occasion' },
      askFor: (occasion: string) => `Ask about ${occasion} services on WhatsApp`,
    },
    why: {
      eyebrow: 'Why Soso?',
      titleLines: ['Small details,', 'a big difference.'],
      items: [
        { title: 'Total privacy', text: 'A fully ladies-only space, calm and yours.' },
        { title: 'Attention to detail', text: 'We care about every detail that brings out your beauty.' },
        { title: 'We come to you', text: 'Home service with full equipment across Doha.' },
        { title: 'Easy to reach', text: 'One WhatsApp message is all it takes.' },
      ],
    },
    how: {
      eyebrow: 'How to book',
      title: 'Three steps only.',
      items: [
        { title: 'Choose your service', text: 'Browse our services and pick what suits you.' },
        { title: 'Message us on WhatsApp', text: 'Ask about details and available times.' },
        { title: 'Enjoy the experience', text: 'In the salon or in the comfort of your home.' },
      ],
    },
    cta: {
      titleLines: ['Ready', 'for your new look?'],
      body: 'Message us now and we will arrange your appointment, in the salon or at home.',
      button: 'Book on WhatsApp',
    },
    footer: {
      address: 'Address',
      hours: 'Opening hours',
      phone: 'Phone',
      instagram: 'Instagram',
      whatsapp: 'WhatsApp',
      map: 'Location on the map',
      copyright: '© 2026 Soso Ladies Salon · soso-ladies.qa',
    },
    sticky: {
      title: 'Book your appointment',
      sub: 'Fast reply on WhatsApp',
      button: 'WhatsApp',
    },
    messages: {
      booking: 'Hi Soso, I would like to book an appointment.',
      service: (service: string) => `Hi Soso, I would like to ask about your ${service} packages.`,
      consultation: 'Hi Soso, I would like to book a free permanent-makeup consultation.',
      occasion: (occasion: string) => `Hi Soso, I would like to ask about ${occasion} services.`,
      homeVisit: 'Hi Soso, I would like to book a home service.',
    },
    carousel: {
      label: 'A look at our services',
      slide: (i: number, n: number, name: string) => `${name}, slide ${i} of ${n}`,
      goTo: (name: string) => `Show: ${name}`,
      previous: 'Previous slide',
      next: 'Next slide',
      pause: 'Pause slideshow',
      play: 'Play slideshow',
      slides: { makeup: 'Makeup', facial: 'Facial care', hair: 'Hair', henna: 'Henna' },
    },
    browseServices: 'Browse services',
    allServices: 'All services',
    learnMore: 'Learn more',
    pages: {
      services: {
        eyebrow: 'Our services',
        titleLines: ['Everything you need,', 'in one place.'],
        lead: 'Choose a service, then ask us about the package that suits your occasion.',
        imageAlt: 'Nail care',
      },
      homeService: {
        eyebrow: 'Home service · Doha',
        titleLines: ['We come to you,', 'wherever you are.'],
        lead: 'If home is where you are most comfortable, we come to you with everything we need and the same care as the salon.',
        imageAlt: 'A makeup artist with a client at home',
      },
      about: {
        eyebrow: 'About Soso',
        titleLines: ['We care for you', 'like a guest in our home.'],
        lead: 'Soso is a fully ladies-only salon, calm and private.',
        imageAlt: 'Hair styling at the salon',
      },
      gallery: {
        eyebrow: 'Gallery',
        titleLines: ['Inside', 'Soso.'],
        lead: 'A look at the salon and our services.',
        imageAlt: 'Henna on a hand',
      },
      contact: {
        eyebrow: 'Contact',
        titleLines: ['We would love', 'to hear from you.'],
        lead: 'Message us on WhatsApp and we will arrange your appointment, in the salon or at home.',
      },
    },
    servicesPreview: {
      eyebrow: 'Our services',
      titleLines: ['Everything you need,', 'in one place.'],
    },
    homeTeaser: {
      eyebrow: 'Home service',
      titleLines: ['We come to you,', 'wherever you are.'],
      body: 'If home is where you are most comfortable, we come to you with everything we need and the same care, across Doha.',
      cta: 'About the home service',
      imageAlt: 'A makeup artist with a client at home',
    },
    homeVisit: {
      factsLabel: 'The home service',
      facts: [
        ['Ladies', 'only'],
        ['Full', 'equipment'],
        ['Across', 'Doha'],
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Three steps only.',
      steps: [
        { title: 'Choose a service', text: 'Browse the services available at home.' },
        { title: 'Message us on WhatsApp', text: 'Pick the time and address that suit you.' },
        { title: 'We come to you', text: 'With everything we need and the same salon care.' },
      ],
      servicesEyebrow: 'Available at home',
      servicesTitle: 'Home services',
      cta: 'Book a home service',
    },
    aboutPage: {
      storyEyebrow: 'Our story',
      videoEyebrow: 'A glimpse of Soso',
      videoTitle: 'Inside the salon.',
    },
    brandStrip: 'Salon identity',
    gallery: {
      open: (alt: string) => `Enlarge image: ${alt}`,
      close: 'Close',
      previous: 'Previous image',
      next: 'Next image',
      alts: {
        makeup: 'A makeup artist with a client',
        facial: 'A facial treatment',
        hair: 'Hair styling',
        henna: 'Henna on a hand',
        manicure: 'Nail care',
        pedicure: 'A pedicure session',
      },
    },
    contactPage: {
      whatsapp: 'WhatsApp',
      whatsappHint: 'The fastest way to book',
      phone: 'Phone',
      instagram: 'Instagram',
      address: 'Address',
      hours: 'Opening hours',
      openMap: 'Open the location on the map',
      mapTitle: 'Salon location on the map',
      empty: 'Contact details are coming soon.',
    },
  },
} as const;

export type Strings = (typeof strings)[Lang];
